//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team15_SEP2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveDetail
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public double ActivityScore { get; set; }
        public double EventScore { get; set; }
        public int TotalScore { get; set; }
        public int SemesterId { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual InformationStudent InformationStudent { get; set; }
    }
}
