//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team15_SEP2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.RegisterEvents = new HashSet<RegisterEvent>();
        }
        public int Id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trườnng này")]
        public string NameEvent { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trườnng này")]
        public System.DateTime StartDate { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trườnng này")]
        public System.DateTime EndDate { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trườnng này")]
        public System.TimeSpan StartTime { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trườnng này")]
        public System.TimeSpan EndTime { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trườnng này")]
        public string Content { get; set; }
        public string Event_Image { get; set; }
        public int EventTypeId { get; set; }
        public int EventStatusId { get; set; }
        public string ReasonCancel { get; set; }
        public string ReasonReject { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTo { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTo { get; set; }
        public string ApproveEventBy { get; set; }
        public Nullable<System.DateTime> ApproveEventTo { get; set; }
        public string RejectEventBy { get; set; }
        public Nullable<System.DateTime> RejectEventTo { get; set; }
        public string ReqCancelBy { get; set; }
        public Nullable<System.DateTime> ReqCancelTo { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelTo { get; set; }
        public string ReasonRejectCancel { get; set; }
        public Nullable<int> ScheduleAutoCancelId { get; set; }
        public Nullable<int> ScheduleRemindId { get; set; }
        public Nullable<int> ScheduleAutoChangeStatusId { get; set; }
        public Nullable<int> ScheduleAutoCancelReqCancelEventId { get; set; }
        public Nullable<int> SemesterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterEvent> RegisterEvents { get; set; }
        public virtual EventStatu EventStatu { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
