//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team15_SEP2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InformationStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformationStudent()
        {
            this.RegisterEvents = new HashSet<RegisterEvent>();
            this.ArchiveDetails = new HashSet<ArchiveDetail>();
        }
        public string StudentId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        public string Full_Name { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Số điện thoại này không hợp lệ")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        public int CoursesId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        public int DepartmentId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        public int MajorsId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập vào trường này")]
        public string Class { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> AtExpiredReqRemove { get; set; }
        public Nullable<int> ScheduleReqRemoveId { get; set; }
        public string userReqRemoveId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Department Department { get; set; }
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterEvent> RegisterEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveDetail> ArchiveDetails { get; set; }
    }
}
