//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team15_SEP2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterEvent
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string StudentId { get; set; }
        public bool Attendances { get; set; }
        public Nullable<System.DateTime> AttendancesTo { get; set; }
        public string AttendancesBy { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual InformationStudent InformationStudent { get; set; }
    }
}
